### ISSUE TITLE
[bug] returns wrong error when item_storage is full

### ISSUE THREAD

**Issue by Merith-TK** [SirEdvin/UnlimitedPeripheralWorks#3] opened 2022-08-05 19:54 UTC
![image](https://user-images.githubusercontent.com/10422110/183150931-387a4f90-ea7e-4bde-a15d-43000fdc1d73.png)

before and after I increased item_storage size

**Comment by SirEdvin** [comment] 2022-10-16 18:20
I can't reproduce it with described case (works for me and ExtenderDrawer), so I need more detail. Or world copy, if this possible :)

**Comment by Merith-TK** [comment] 2022-10-19 01:21
Was using Create item Vaults

**Comment by SirEdvin** [comment] 2023-04-27 18:09
So ... I will close this for now, because I wan't able to reproduce this properly ...

**Comment by Merith-TK** [comment] 2023-04-27 18:20
IIRC I had two create item vaults
Left was filled to the max
Right wasnt

I tried to `right.PullItem("left")`

if I recall correctly that is

**Comment by SirEdvin** [comment] 2023-05-02 08:06
I will take a look after porting everything to 1.19.4, I guess :)

**Comment by SirEdvin** [comment] 2023-05-24 12:49
So, this is happening because now or in older versions create not always correctly processing fabric requests (I suppose).

Due to #16 this issue is not longer relevant, because create integration will be in place

**Closed as completed by SirEdvin** 2023-05-24 12:49 UTC
Labels: wontfix
