### ISSUE TITLE
`pushItems` and `pullItems` returns 2x the real transfer count

### ISSUE THREAD

**Issue by runi95** [SirEdvin/UnlimitedPeripheralWorks#38] opened 2024-06-21 00:23 UTC
Reproduction steps:

1. Place down Chest
2. Put 26 Dirt into slot 1 of Chest
3. Place down Advanced Turtle facing the Chest
4. Right click the Advanced Turtle to open the turtle interface
5. \> `lua`
6. lua> `peripheral.call("front", "pushItems", "front", 1, nil, 2)`

The peripheral call returns 52 (transferred items), but the chest only contains 26 Dirt which has now been moved to slot 2. This does not happen with just CC: Tweaked installed alone, but as soon as `UnlimitedPeripheralWorks` is added the bug occurs.

NOTE: This bug only seems to appear when pushing or pulling items within the same inventory (ex: When wanting to move an item from one slot to another within the same chest), but as far as I can tell it does not seem to occur when transferring items between 2 separate inventories.

**Comment by SirEdvin** [comment] 2024-06-21 08:34
Linking CC:T [issue](https://github.com/cc-tweaked/CC-Tweaked/issues/1867)

**Comment by SirEdvin** [comment] 2024-06-26 18:00
@runi95 which version of UPW and Peripheralium you using? I can't reproduce this behaviour

**Comment by runi95** [comment] 2024-06-27 00:17
@SirEdvin Not sure if it matters, but I've been running this on Fabric instead of Forge and I'm encountering this issue when running on:
- Minecraft `1.20.1`
- Fabric loader `0.15.11`

With the following mods:
- CC:Tweaked `1.111.0`
- UnlimitedPeripheralWorks `1.4.3`
- Peripheralium `0.6.15`
- *Fabric API `0.92.2`
- *Fabric Language Kotlin `1.11.0`
- *Forge Config API `8.0.0`

*Are required to run these mods on Fabric

**Comment by SirEdvin** [comment] 2024-06-27 14:37
I find it very ironic that Fabric API upgrade cause this issue

**Comment by SirEdvin** [comment] 2024-06-27 15:06
But of course, the root of this issue was my code :)

**Comment by runi95** [comment] 2024-06-27 18:07
Hehe, I definitely feel you! I found it pretty odd too and thought it was a CC:Tweaked issue to begin with. Until I started testing with CC:Tweaked alone.
Still found an oddity in how CC:Tweaked performed, but it wasn't quite the same issue.

**Comment by SirEdvin** [comment] 2024-08-20 19:41
Fixed in 1.4.4 release

**Closed as completed by SirEdvin** 2024-08-20 19:41 UTC
Labels: awaiting release
